version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  appy: #name of the second service
    build: ./ # specify the directory of the Dockerfile
    ports:
      - "8125:8125" #specify ports forewarding
    links:
      - database # link this service to the database service
    depends_on:
      - database
    #command: ["./waitforit.sh", "database:27017", "--", "gulp", "seed"]


  database: # name of the third service
    image: mongo # specify image to build container from